### ISSUE TITLE
Aggregation doesn't work when using same function for different columns

### ISSUE THREAD

**Issue by gabriel19913** [jcpsantos/sparta#8]
I am trying to use the function aggregation to sum two different cols, and it is not working.
Looks like it made the operation just for the second one in the dictionary.

My dictionay is:
`  agg = {F.mean: 'peso_real_unitario', F.sum: 'quantidade', F.sum: 'peso_real_unitario', F.count: 'peso_real_unitario', F.stddev: 'peso_real_unitario'}`

However when I print the variable `agg` the returned value is:
`{<function mean at 0x7f2b3aa8cca0>: 'peso_real_unitario', <function sum at 0x7f2b3aa8cb80>: 'peso_real_unitario', <function count at 0x7f2b3aa8ca60>: 'peso_real_unitario', <function stddev at 0x7f2b3aa90550>: 'peso_real_unitario'}`

So how it is possible to see, the column `quantidade` is not summed. I try to invert the positions between the columns `quantidade` and `peso_real_unitario` in the dictionary, and when I do this, the column peso_real_unitario is not summed.

Is there any way to fix this behavior?

**Comment by jcpsantos** [comment]
Upload a new release, correcting this bug.
Now when you have columns that have the same type of aggregation, just pass the name of these columns in a list, as in the example:
```
agg = {F.sum:['new_confirmed','order_for_place']}
cols = ['state', 'city']
df = aggregation(df, 'date', cols, agg)
```
